version: 2
orbs:
  slack: circleci/slack@4.3
jobs:
  build:
    docker:
      - image: circleci/node:14.17.0
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - deps1-{{ .Branch }}-{{ checksum "yarn.lock" }}
              # fallback to using the latest cache if no exact match is found
            - deps1-
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Build
          command: yarn build
      - run:
          name: Firebase Deploy
          command: firebase deploy --token $FIREBASE_TOKEN --non-interactive
