version: 2
orbs:
  slack: circleci/slack@4.3
jobs:
  build:
    docker:
      - image: circleci/node:14.17.0
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - deps1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - deps1-
          filters:
            branches:
              only: master
      - run:
          name: Install Dependencies
          command: yarn install
          filters:
            branches:
              only: master
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
          filters:
            branches:
              only: master
      - run:
          name: Build
          command: yarn build
          filters:
            branches:
              only: master
      - run:
          name: Firebase Deploy
          command: ./node_modules/.bin/firebase deploy --only hosting --project "$FIREBASE_PROJECT_ID" --token "$FIREBASE_TOKEN"
          filters:
            branches:
              only: master