- name: Deploy Preview Channel
    uses: FirebaseExtended/action-hosting-deploy@v0
    with:
      repoToken: '${{ secrets.FIREBASE_TOKEN }}'
      firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_BLOG_PROJECT }}'
      expires: 7d
      projectId: gdsc-dju-blog
      channelId: preview