name: Deploy to Preview Channel

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches-ignore:
      - master
      - develop
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    environment:
      name: Preview
      url: ${{ steps.run_firebase_preview.outputs.details_url }}
    steps:
      - uses: actions/checkout@v2
      - run: 'yarn && yarn build'
        env:
          CI: ""
        # Add additional build steps here
      - uses: FirebaseExtended/action-hosting-deploy@v0
        id: run_firebase_preview
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_BLOG_PROJECT }}'
          projectId: gdsc-dju-blog
          channelId: ' pr-${{ github.event.number }}-${{ github.event.pull_request.head.ref }} '
          expires: 14d
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: '
            The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed.
            > Contributor: ${{github.actor}}
            
            - Event Status: ${{github.event_name}}
            - URL: ${{steps.run_firebase_preview.outputs.details_url}}
            - Build Time: ${{steps.run_firebase_preview.outputs.expire_time}}
            '
