name: Deploy to Preview Channel

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches-ignore:
      - master
      - develop
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    environment:
      name: Preview
      url: ${{ steps.run_firebase_preview.outputs.details_url }}
    steps:
      - uses: actions/checkout@v2
      - run: 'yarn && yarn build'
        env:
          CI: ""
        # Add additional build steps here

      - uses: actions/checkout@v2
      - id: shortsha
        run: echo "::set-output name=shortsha::$(git rev-parse --short HEAD)"
      outputs:
        shortsha: ${{steps.shortsha.outputs.shortsha}}
      - uses: FirebaseExtended/action-hosting-deploy@v0
        id: run_firebase_preview
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_BLOG_PROJECT }}'
          projectId: gdsc-dju-blog
          channelId: ' pr-${{ shortsha.outputs.shortsha }}-${{ github.event.pull_request.head.ref }} '

          expires: 14d
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
      - name: Discord Message Notify
        uses: appleboy/discord-action@0.0.3
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          color: "#4285f4"
          args: |
            gdsc-blog-fe has been deployed to Preview channel
            `Contributor`: ${{github.actor}}
            `Event Status` ${{github.event_name}}
            `URL` <${{steps.run_firebase_preview.outputs.details_url}}>
            `Build Time` ${{steps.run_firebase_preview.outputs.expire_time}}
